#!/usr/bin/env python3
"""
generate_domain_mapping.py
Scan an iOS project directory tree and generate a starter domain_mapping.yaml.

Usage:
  python scripts/generate_domain_mapping.py --workspace /path/to/your/ios/project
  python scripts/generate_domain_mapping.py --workspace /path/to/ios --output domain_mapping.yaml
"""

import argparse
import os
import sys
from pathlib import Path

# Heuristic patterns: if a directory name contains any of these keywords,
# assign the corresponding domain. More specific patterns are listed first.
HEURISTICS = [
    # Networking
    (["network", "api", "http", "request", "response", "endpoint", "service"],  "networking"),
    # Authentication
    (["auth", "login", "signin", "signup", "account", "credential", "token"],   "auth"),
    # Data / Persistence
    (["database", "coredata", "realm", "sqlite", "storage", "cache", "persist", "repository"], "data"),
    # UI / Presentation
    (["viewcontroller", "viewmodel", "view", "screen", "ui", "cell", "widget", "component"], "ui"),
    # Navigation / Routing
    (["navigation", "router", "coordinator", "routing", "deeplink"],            "navigation"),
    # Analytics
    (["analytics", "tracking", "metric", "logging", "event", "telemetry"],      "analytics"),
    # Push / Notifications
    (["push", "notification", "apns", "fcm", "remote"],                         "push"),
    # Media
    (["media", "image", "video", "audio", "camera", "photo", "player"],         "media"),
    # Utilities / Extensions
    (["util", "helper", "extension", "common", "shared", "base", "foundation"], "utilities"),
    # Map / Location
    (["map", "location", "geo", "coordinate", "gps", "mapkit"],                 "maps"),
    # Settings
    (["setting", "config", "preference", "onboarding"],                         "settings"),
    # Payment
    (["payment", "purchase", "billing", "checkout", "iap", "subscription"],     "payments"),
    # App lifecycle
    (["appdelegate", "scenedelegate", "app", "lifecycle", "launch"],            "app"),
]


def infer_domain(dir_name: str) -> str:
    lower = dir_name.lower()
    for keywords, domain in HEURISTICS:
        if any(k in lower for k in keywords):
            return domain
    return dir_name.lower().replace(" ", "_")


def generate_mapping(workspace: str, max_depth: int = 3) -> dict:
    """
    Walk the workspace up to max_depth and collect directories that contain
    Swift or ObjC source files.
    Returns {relative_path_prefix: domain}.
    """
    workspace_path = Path(workspace).expanduser().resolve()
    if not workspace_path.exists():
        print(f"Error: workspace path does not exist: {workspace_path}", file=sys.stderr)
        sys.exit(1)

    SKIP_DIRS = {
        "Pods", ".git", ".build", "build", "DerivedData",
        ".xcodeproj", ".xcworkspace", ".framework", ".xcframework",
        "__pycache__", "node_modules",
    }

    SOURCE_EXTENSIONS = {".swift", ".m", ".mm", ".h"}

    # Collect all directories (up to max_depth) that contain source files
    dir_has_sources: dict[Path, bool] = {}

    for root, dirs, files in os.walk(workspace_path):
        root_path = Path(root)
        try:
            depth = len(root_path.relative_to(workspace_path).parts)
        except ValueError:
            continue

        if depth > max_depth:
            dirs.clear()
            continue

        # Prune skip directories
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]

        has_sources = any(Path(f).suffix in SOURCE_EXTENSIONS for f in files)
        if has_sources:
            dir_has_sources[root_path] = True

    # Build mapping: use the directory relative to workspace as the prefix key
    mapping = {}
    for dir_path in sorted(dir_has_sources.keys()):
        try:
            rel = dir_path.relative_to(workspace_path)
        except ValueError:
            continue
        parts = rel.parts
        if not parts:
            continue
        # Use the last component for domain inference (most specific)
        domain = infer_domain(parts[-1])
        prefix = str(rel) + "/"
        mapping[prefix] = domain

    return mapping


def write_yaml(mapping: dict, output_path: str, workspace: str):
    lines = [
        "# domain_mapping.yaml",
        "# Auto-generated by scripts/generate_domain_mapping.py",
        f"# Workspace: {workspace}",
        "#",
        "# Review and customize the domain names below.",
        "# The tool uses longest-prefix matching, so more specific paths",
        "# take precedence. Add, remove, or rename entries as needed.",
        "",
        "mappings:",
    ]

    if not mapping:
        lines.append("  # No source directories found. Check your workspace path.")
    else:
        current_top = None
        for prefix, domain in sorted(mapping.items()):
            top = prefix.split("/")[0]
            if top != current_top:
                lines.append(f"\n  # ── {top} ──")
                current_top = top
            lines.append(f"  {prefix}: {domain}")

    content = "\n".join(lines) + "\n"

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Written {len(mapping)} entries to {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate a starter domain_mapping.yaml from your iOS project structure."
    )
    parser.add_argument("--workspace", required=True, help="Path to iOS project root")
    parser.add_argument("--output", default="domain_mapping.yaml",
                        help="Output file path (default: domain_mapping.yaml)")
    parser.add_argument("--depth", type=int, default=3,
                        help="Max directory depth to scan (default: 3)")
    args = parser.parse_args()

    print(f"Scanning {args.workspace} (depth={args.depth})...")
    mapping = generate_mapping(args.workspace, max_depth=args.depth)
    print(f"Found {len(mapping)} source directories")

    write_yaml(mapping, args.output, args.workspace)
    print(f"\nNext steps:")
    print(f"  1. Review {args.output} and adjust domain names")
    print(f"  2. Update workspace.path in config.yaml")
    print(f"  3. Run: python cli.py build")


if __name__ == "__main__":
    main()
